[package]
name = "proexel-service"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
appcore-bin = { path = "../../../core/AppCore-Runtime/crates/appcore-bin", default-features = false }
appcore-security = { path = "../../../core/AppCore-Runtime/crates/appcore-security" }
proexel-application.workspace = true
proexel-domain.workspace = true
proexel-infrastructure.workspace = true
serde.workspace = true
serde_json.workspace = true

[[bin]]
name = "proexel-service"
path = "src/main.rs"
